dist: bionic

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: change

################################################################################

_stage_base: &_stage_base
  before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - export WORKRAVE_FULL_TAG=`git describe --tags --abbrev=10`
    - export WORKRAVE_TAG=`git describe --abbrev=0`
    - export WORKRAVE_COMMIT_COUNT=`git rev-list ${WORKRAVE_TAG}..HEAD --count`
    - export WORKRAVE_COMMIT_HASH=`git rev-parse HEAD`
    - export WORKRAVE_BUILD_DATE=`date +"%Y%m%d"`
    - export WORKRAVE_BUILD_DATETIME=`date --iso-8601=seconds`
    - export WORKRAVE_BUILD_ID="$WORKRAVE_BUILD_DATE-$WORKRAVE_FULL_TAG"
    - export WORKRAVE_UPLOAD_DIR="snapshots/v1.10/$WORKRAVE_BUILD_ID"
    - |
        if [ ${TRAVIS_OS_NAME} = "osx" ]; then
          # compilation with system wide gettext fails at the link stage with missing symbols...
          brew install gettext qt5 python3
          brew link gettext --force
          brew linkapps qt5
          brew outdated cmake || brew upgrade cmake

          pip3 install --user Jinja2==2.8 # required for dbus support, system (distro) wide include paths are ignored

        elif [ ${TRAVIS_OS_NAME} = "linux" ]; then
          sudo apt-get -y install python3 python3-pip python3-setuptools
          python3 -V
          pip3 -V
        fi

_stage_build_docker: &_stage_build_docker
  <<: *_stage_base
  os: linux
  dist: bionic
  language: cpp
  script: |
    if [[ $DOCKER_IMAGE ]]; then
      IFS=$'\n'
      docker run --rm \
          -v "$TRAVIS_BUILD_DIR:/workspace/source" \
          `printenv | grep -E '^(CONF_ENABLE|CONF_DISABLE||CONF_FLAGS|CONF_GTK_VER|CONFIGURATION|DOCKER_IMAGE|DISTCHECK|TRAVIS_TAG|TRAVIS_BUILD_DIR|TRAVIS_BUILD_NUMBER|TRAVIS_JOB_NUMBER|TRAVIS_REPO_SLUG|TRAVIS_OS_NAME|TRAVIS_BRANCH|WORKRAVE_.*)=' | sed  -e 's/^/-e/g' ` \
          rcaelers/workrave-build:${DOCKER_IMAGE} \
          sh -c "/workspace/source/build/travis/build.sh"
    else
       build/travis/build.sh
    fi

_stage_build_osx: &_stage_build_osx
  <<: *_stage_base
  os: osx
  osx_image: xcode11
  language: cpp
  script:
    - build/travis/build.sh

jobs:
  include:
    - stage: prepare
      language: cpp
      script: |
      <<: *_stage_base

    ###########################################################################
    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,experimental,gconf,gstreamer,exercises"
        CONF_DISABLE=""
        DOCKER_IMAGE="ubuntu-xenial"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,experimental,gconf,gstreamer,exercises"
        CONF_DISABLE=""
        DOCKER_IMAGE="ubuntu-bionic"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,experimental,gconf,gstreamer,exercises"
        CONF_DISABLE=""
        DOCKER_IMAGE="ubuntu-eoan"
        DISTCHECK="yes"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,experimental,gconf,gstreamer,exercises"
        CONF_DISABLE=""
        DOCKER_IMAGE="ubuntu-focal"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,experimental,gconf,gstreamer,exercises"
        CONF_DISABLE=""
        DOCKER_IMAGE="ubuntu-groovy"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        DOCKER_IMAGE="ubuntu-eoan"
        CONF_GTK_VER="2"
        CONF_ENABLE="gsettings,,exercises,xml,gconf,distribution,experimental"
        CONF_DISABLE="pulse,xfce,gnome3,gstreamer,dbus,mate,indicator"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,pulse,dbus,experimental,gstreamer,exercises,xml"
        CONF_DISABLE="gsettings,gconf,indicator,xfce,mate,debug,distribution,tests,tracing"
        DOCKER_IMAGE="ubuntu-eoan"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONF_GTK_VER="3"
        CONF_ENABLE="gnome3,gsettings,xml,pulse,indicator,xfce,mate,dbus,distribution,experimental,gconf,gstreamer,exercises"
        CONF_DISABLE=""
        DOCKER_IMAGE="debian-testing"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONFIGURATION="Release"
        DOCKER_IMAGE="mingw-gtk2"
      <<: *_stage_build_docker

    - stage: build
      env: >
        COMPILER="gcc"
        CONFIGURATION="Debug"
        DOCKER_IMAGE="mingw-gtk2"
      <<: *_stage_build_docker

stages:
    - name: prepare
      if: tag IS present AND tag =~ ^v1_.*$ AND type = push
    - name: build
      if: (tag IS NOT present) OR (tag != ppa)
    - name: catalog
      if: ((tag IS NOT present) OR (tag != ppa)) AND type = push
    - name: release
      if: tag IS present AND tag =~ ^v1_.*$ AND type = push
    - name: ppa
      if: tag IS present AND (tag =~ ^v1_.*$ OR tag = ppa) AND type = push
